name: Alphapaste Auto-Save

on:
  repository_dispatch:
    types: [create_paste]

jobs:
  save:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Save new paste file
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          FILE_NAME="${{ github.event.client_payload.fileName }}"
          CONTENT="${{ github.event.client_payload.content }}"
          echo "$CONTENT" > "$FILE_NAME"
          git config user.name "AlphaPasteBot"
          git config user.email "alpha@zeta.io"
          git add "$FILE_NAME"
          git commit -m "Add new paste $FILE_NAME"
          git push "https://${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" HEAD:main
